# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "2897d2f3518b01e174933182a301a9185c6c05645677eaff272b213c7fe748f3"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "682e6ace57da617d8c253dee37a7386278e38c6bd03cdf436b1ac9703d430b73"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62bdb4580fe1cbc7f5f88b0b09f7be2abf7204d1aa1182b8e2484a6ddef68055"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e3bed21e5c6d1aae3c017e38b1c9bb1b8c9df76ac2dfd66c848743301566108"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy"
  desc "NurProxy orchestrator — reverse proxy and DNS management dashboard"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy"]
  end

  # No zap stanza required

end
