# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy-agent" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "98a4dcfc3fa86fb578eeda8e76145ce61548f971d6f3a94f79e348ad359fab0a"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "036d2c5e7e2edf15ab4a123bf075b8855098b5d651ab9b9df574fa9c7ec1afc3"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6aa21b34ac648833d0e51cf46f6fa44de8ed067da8e2dc748756ca8c8fbc03c7"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "131289ff8df60a9ed5dfc09b1fa9fafc8751c898199d3e6eab8e63a771426a0f"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy-agent"
  desc "NurProxy agent — manages a local reverse proxy on an edge server"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy-agent"]
  end

  # No zap stanza required

end
