# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy-agent" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "2ae4c464f7eaef88f45c7ef3d2541a968c1e5a31cd3280946c27cad07b62a2f0"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "825c030ea595da6808c4825d28732d9ff1650bf564be035134d580f8701383b7"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "533dbb47ddbab428dda88cda9c12407819c5866265e740b45a75e7a6b46e1f36"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "939c482485614f7c39b26a888193791ef3b879e25f541762fe76effaa1afb6e2"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy-agent"
  desc "NurProxy agent — manages a local reverse proxy on an edge server"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy-agent"]
  end

  # No zap stanza required

end
