# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7b7494fe5a745ac5f346a08a049a23ca5cfbd6ac8e6a4eb2070f72ed3ddcd445"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d5c0cb0d48dc144b7d5f7d966135cef759247c2fefe6e855e4aa2671a8fcdf2"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ccb0595f3386c296a1ae1a82fce678337e50d4867eddec9fd50e70be290462d"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c20503ccbd5219207eb94aac8550659d46e655359b277a178cc2f153c5649240"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy"
  desc "NurProxy orchestrator — reverse proxy and DNS management dashboard"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy"]
  end

  # No zap stanza required

end
