# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "745cae6ccf279e2e5ea8d346e2c173fcd470bdb4bde33c31ffe606b0f3c09b76"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f498c95b3c330b3cc21eab2538950cbcd32ca1abacb3dfd49d31282be13597b5"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7770c90907fac44614797fde17269dc0ea919dff06f4fa210b4704e6809e455d"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e8a8349ae42319c2ab0601e1ce69980513dbfa8959e3d8b21c5b1840869b1da"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy"
  desc "NurProxy orchestrator — reverse proxy and DNS management dashboard"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy"]
  end

  # No zap stanza required

end
