# This file was generated by GoReleaser. DO NOT EDIT.
cask "nurproxy-agent" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e09518cd2e774a63624d1b63a150c4474f4fbdc1badb7bd140ba0fb577da9cd7"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e194cdb6aa3a50dc33bb5beb0e3de7dbbefaa6ebf9b3956a1978993aec26ec28"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f304294d1fc8955df93bb067cee7b7ad318d84ded1dba70b781765d2a8c5c319"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a538474269ef520e6f5fc03ff3e060c0ba24f2aba5178b6366f850cef39cd799"
      url "https://github.com/NurRobin/NurProxy/releases/download/v#{version}/nurproxy-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nurproxy-agent"
  desc "NurProxy agent — manages a local reverse proxy on an edge server"
  homepage "https://github.com/NurRobin/NurProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nurproxy-agent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nurproxy-agent"]
  end

  # No zap stanza required

end
